name: CI/CD Pipeline
on: [push]

jobs:
  # Declare 'build' job
  build:
     # Use Linux-based Github-hosted runner
    runs-on:  ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.16.0
    - name: Install project dependencies
      run: npm ci
    - name: Run unit test
      run: npm run test -- --watch=false --browsers=ChromeHeadless
