name: CI/CD Pipeline
on: [push]

jobs:
  build-test-deploy:
     # Use Linux-based Github-hosted runner
    runs-on:  ubuntu-latest
    steps:
    # Build stage
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.16.0
    - name: Install project dependencies
      run: npm ci
    # Test stage
    - name: Run unit test
      run: npm run test -- --watch=false --browsers=ChromeHeadless
    # Deploy stage
    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  
